version: "3.7"

services:
  kerberos-sidecar:
    # image: kerberos-sidecar
    # hostname: kerberos-sidecar
    environment:
      - TZ=Europe/Istanbul
      - SECRETS=/secrets
      - KEYTAB=client.keytab
      # - PRINCIPAL=${USERNAME}
      - PRINCIPAL=${USERNAME}@${USERDNSDOMAIN}
      - PASSWORD=${PASSWORD}
      - VOLUME=/kerberos-sidecar
      - KRB5_CONFIG=/kerberos-sidecar/krb5.conf
      - KRB5CCNAME=FILE:/kerberos-sidecar/krb5cc
      - REKINIT_PERIOD=28800
    build:
      context: ./app
      dockerfile: Dockerfile
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    restart: on-failure
    volumes:
      - sidecar-volume:/kerberos-sidecar:rwx
      # - ./secrets/client.keytab:/secrets/client.keytab
    secrets:
      # - client-keytab
      - source: client-keytab
        target: /secrets/client.keytab

volumes:
  sidecar-volume:
    external: false
    name: kerberos-sidecar

secrets:
  client-keytab:
    file: ./secrets/client.keytab
    # external: true
    # name: client.keytab